<!DOCTYPE html>
 
<html lang="en">
  <head>
    <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XMCMYLZC7L"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XMCMYLZC7L');
</script>
<!-- End of GTAG-->
    <title>Vision Solar</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
      body {font-family: "Lato", sans-serif; margin: 0;}
    </style>
    <script
        src="https://code.jquery.com/jquery-3.3.1.js"
        integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous">
    </script>
    <script> 
      $(function(){
        $("#header").load("/assets/header.html"); 
        $("#privacy-policy").load("/assets/privacy_policy.html"); 
        $("#footer").load("/assets/footer.html"); 
      });
    </script> 
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <script src="javascript/slideshow.js"></script>
    <link rel="stylesheet" href="/css/global.css">
    <link rel="stylesheet" href="/css/index.css">
    <link rel="stylesheet" href="/css/navbar.css">
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/call_to_action_button.css">

  </head>
  <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XMCMYLZC7L"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XMCMYLZC7L');
</script>
<?php include '../../assets/header.php';?>
    <div id="privacy-policy"></div>

    <div>
      <div>
        <div class="full-container" style="width:100%">

        <div class="parent-content">
          <div class="parent-content text-content-centered">
            <h2 class="text-center">Inflation Busters!</h2>
            <p class="text-center">Installing solar panels on your home with Vision Solar is not only a great way to reduce your energy bills and protect the environment, but it can also help you fight inflation. With the current rate of inflation in Ireland at around 4.5% (as of February 2023), it's becoming increasingly important to find ways to safeguard your purchasing power and protect your financial future.</p>
            <p class="text-center">By producing your own electricity with solar panels, you can protect yourself against the rising costs of electricity and safeguard your financial future. For example, let's say you invest €10,000 in a solar energy system with Vision Solar today. Assuming an average inflation rate of 4.5%, in five years' time, that €10,000 would only have the purchasing power of around €8,162, and in ten years' time, it would be worth around €6,635.</p>
            <p class="text-center">However, by installing solar panels, you can hedge against rising electricity prices and inflation, and potentially save thousands of euros over the lifetime of your system. Moreover, if you have excess energy generated by your solar panels, you may be able to sell it back to the grid and receive credit on your electricity bill. This means that you can benefit from not only reducing your own energy bills but also potentially earning revenue from your solar energy system.</p>
            <p class="text-center">At Vision Solar, we can help design and install a custom solar energy system that meets your energy needs and budget. Our team of experts can help you navigate the grant application process and ensure that you take full advantage of available incentives and tax credits. Contact us today to learn more about how we can help you fight inflation with solar energy.</p>
          </div>

          <br />

        <div class="cta_container">

          <a href="../instant_quote_calculator.php">
            <button class="cta-button-quote" type="button"><p class=cta_button_text>Get an Instant Quote! <i class="fa-solid fa-arrow-right"></i></p></button>
          </a>
        </div>
            
        </div>
        </div>
        <span class="spacing"></span>
        <?php include '../../assets/footer.php';?>
      
    </body>
</html>